all:
	h5cc mainctl.c UDPdiscover.c -o mainctl -I/usr/local/include/CUnit -I/home/odroid/projects/TangerineSDR-notes/includes -I/usr/local/include/json-c -ljson-c -luv -lconfig -lcunit  -lpthread -lm 
