all:
	h5cc mainctl.c UDPdiscover.c -o mainctl -I/usr/local/include/digital_rf -I/home/odroid/projects/TangerineSDR-notes/includes -I/usr/local/include/json-c -ljson-c -luv -lconfig -lcunit -l:libhdf5.so -ldigital_rf -lpthread -lm -lfftw3 -lfftw3f
